import { cosmetic_1_img } from "../assets/images";

const cosmetics = [
    {
        id: 1,
        name: "Lipstick",
        description: "Son môi màu sắc tươi sáng.",
        price: 500000,
        discount: 10,
        quantitySold: 150,
        isLove: true,
        image: cosmetic_1_img,
    },
    {
        id: 2,
        name: "Foundation",
        description: "Kem nền mịn màng và lâu trôi.",
        price: 500000,
        discount: 10,
        quantitySold: 200,
        isLove: false,
        image: cosmetic_1_img,
    },
    {
        id: 3,
        name: "Mascara",
        description: "Mascara chống nước và làm dày mi.",
        price: 500000,
        discount: 10,
        quantitySold: 300,
        isLove: true,
        image: cosmetic_1_img,
    },
    {
        id: 4,
        name: "Blush",
        description: "Phấn má hồng mang lại vẻ rạng rỡ tự nhiên.",
        price: 500000,
        discount: 10,
        quantitySold: 120,
        isLove: false,
        image: cosmetic_1_img,
    },
    {
        id: 1,
        name: "Lipstick",
        description: "Son môi màu sắc tươi sáng.",
        price: 500000,
        discount: 10,
        quantitySold: 150,
        isLove: true,
        image: cosmetic_1_img,
    },
    {
        id: 2,
        name: "Foundation",
        description: "Kem nền mịn màng và lâu trôi.",
        price: 500000,
        discount: 10,
        quantitySold: 200,
        isLove: false,
        image: cosmetic_1_img,
    },
    {
        id: 3,
        name: "Mascara",
        description: "Mascara chống nước và làm dày mi.",
        price: 500000,
        discount: 10,
        quantitySold: 300,
        isLove: true,
        image: cosmetic_1_img,
    },
    {
        id: 4,
        name: "Blush",
        description: "Phấn má hồng mang lại vẻ rạng rỡ tự nhiên.",
        price: 500000,
        discount: 10,
        quantitySold: 120,
        isLove: false,
        image: cosmetic_1_img,
    },
];

export default cosmetics;
