export { default as DashboardPage } from './DashboardPage';
export { default as StatisticsPage } from './StatisticsPage';
export { default as OrdersManagementPage } from './OrdersManagementPage';
export { default as ServiceManagementPage } from './ServiceManagementPage';
export { default as CollectionsManagementPage } from './CollectionsManagementPage';
export { default as CosmeticsManagementPage } from './CosmeticsManagementPage';
export { default as CoursesManagementPage } from './CoursesManagementPage';
export { default as SettingsPage } from './SettingsPage';
export { default as HelpsPage } from './HelpsPage';
